apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y7tsi50w6-python 
  janus-idp.io/tekton: y7tsi50w6-python
  backstage.io/kubernetes-id: y7tsi50w6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y7tsi50w6-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml